### ISSUE TITLE
Controls for generation

### ISSUE THREAD

**Issue by R7E** [brisvag/gibberify#14]
Add controls to be able to tune the sound of words generated.
Add selectors for how often a sound is heard like a hard "g" or "d".
Add selectors for missing sounds like how some languages can't produce a "w".
Add selector for syllable length. You know High Elves are going to be very verbose in their language and try to show off in the length of the words they use. Or possibly have Entish where it takes an hour to say hello.

**Comment by brisvag** [comment]
Added all of this except for syllable length (not sure how to best approach that) in commit ea3567b.

**Comment by brisvag** [comment]
Turned out there was a silly mistake in there. It's now fixed and properly working with 8727050!
